spring:
  application:
    name: blog-comment-service
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/blog_comments
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
      show-sql: true
      generate-ddl: true
    sql:
      init:
        mode: always
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8083
